### ISSUE TITLE
Analytical solution 

### ISSUE THREAD

**Issue by Agasax** [benkeser/pfizerresults#1]
Very nice!

If I'm not mistaken (and as an amateur I might well be) the analytical solution to the mean is this: 
The mean of a beta distribution is alpha/(alpha+beta), so:
  ```r  
posterior_mean_theta <-  alpha_v/(alpha_v+beta_v)
posterior_mean_ve <-  (1-2*posterior_mean_theta)/(1-posterior_mean_theta)
```
giving a mean of 0.946.

**Comment by benkeser** [comment]
Not sure it’s that simple since VE is non-linear transformation of theta. So it’s like a Jensens inequality thing. I think one would have to derive the posterior density of VE and compute the integral to get the posterior mean. Maybe there’s an easy form of the density, I didn’t really try. I’m always ok with Monte Carlo integration 😊

**Comment by Agasax** [comment]
I see my very fundamental mistake! 
Absolutely fine with sampling (it's what I've been using in [this]( https://lmsaxhaug.shinyapps.io/Empirical_bayes_dt/) app, except for the analytical solution to the probability of  difference between two beta distributed variables), I was just curious whether it really was that simple and surprised at how similar results I got. I see the error grows with larger theta and understand why now, thanks!
